from ..days.day08 import *


def test_day08_1():
    a = Pos(0, 0)
    b = Pos(1, 3)
    print(a.anodes(b, 9, 9, True))
    print(a.anodes(b, 9, 9, False))


def test_day08():
    inp = """\
............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............
"""
    p1, p2 = run(inp.splitlines())
    assert p1 == 14
    assert p2 == 34
